title: Sleeptime Markup Language (STML) reference
remote_theme: sighingnow/jekyll-gitbook
url: https://noblerobot.github.io/vscode-stml/
lsi: false
safe: true
timezone: America/Chicago
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
toc:
  enabled: true

