title: Sleeptime Markup Language (STML) reference
theme: just-the-docs
url: https://noblerobot.github.io/vscode-stml/
lsi: false
safe: true
timezone: America/Chicago
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
